### PR TITLE
Add Junits in service-now plugins project and Increase code coverage to atleast 80%

### PR DESCRIPTION
**Pull request by sgarg-CS**

### CODE REVIEW

**Comment by rmstar** [comment]
Why are there changes in src/main/java if this PR is just adding unit tests?

**Comment by sgarg-CS** [comment]
Hi Prashant, this PR is still in progress. We had raised it for our internal review. 

The branch (in this PR): `sgarg-CS:story/Junits`  had been cut from the branch: `sgarg-CS:story/PLUGIN-998` (This [PR](https://github.com/data-integrations/servicenow-plugins/pull/8) is yet to be merged into develop) to make it feasible for writing the JUnit's as it had all the Service Now Multi-Source Plugin business implementation. 

I have converted this PR into a draft.

**Comment by sgarg-CS** [comment]
The Jacoco Code Coverage in the service-now plugins project is 82%. All the JUnit implementation has been completed.

This PR is dependent on the Service Now Batch Multi-Source [PR](https://github.com/data-integrations/servicenow-plugins/pull/8) which is yet to be merged, so I've kept this as a draft PR.

**Comment by sgarg-CS** [comment]
A separate [PR](https://github.com/data-integrations/servicenow-plugins/pull/15) for ServiceNow JUnits was raised that was approved and merged to `develop`. This PR is no longer required.

**Pull request closed without merging**
